// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4FR35hjXWChq_azdT0pvEOlbVivSptU',
    appId: '1:214393173920:web:844adac069512dea4e96c5',
    messagingSenderId: '214393173920',
    projectId: 'recycleapp-6c4e6',
    authDomain: 'recycleapp-6c4e6.firebaseapp.com',
    storageBucket: 'recycleapp-6c4e6.firebasestorage.app',
    measurementId: 'G-8D54XK55GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvG21sRGuqVFR6jMwL3skwVFlpkRsVck',
    appId: '1:214393173920:android:d29d5e0ae4d936414e96c5',
    messagingSenderId: '214393173920',
    projectId: 'recycleapp-6c4e6',
    storageBucket: 'recycleapp-6c4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUHEqGs33knYzsb3Jk_6A1l-mo-J7RCY',
    appId: '1:214393173920:ios:04caa9ad44ceb4564e96c5',
    messagingSenderId: '214393173920',
    projectId: 'recycleapp-6c4e6',
    storageBucket: 'recycleapp-6c4e6.firebasestorage.app',
    androidClientId: '214393173920-67j6p5d0d83gqgc77ft6q09lohf4tnkv.apps.googleusercontent.com',
    iosClientId: '214393173920-dcutidqs2gllpihq4jcjejq60l2a0ncr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUHEqGs33knYzsb3Jk_6A1l-mo-J7RCY',
    appId: '1:214393173920:ios:04caa9ad44ceb4564e96c5',
    messagingSenderId: '214393173920',
    projectId: 'recycleapp-6c4e6',
    storageBucket: 'recycleapp-6c4e6.firebasestorage.app',
    androidClientId: '214393173920-67j6p5d0d83gqgc77ft6q09lohf4tnkv.apps.googleusercontent.com',
    iosClientId: '214393173920-dcutidqs2gllpihq4jcjejq60l2a0ncr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4FR35hjXWChq_azdT0pvEOlbVivSptU',
    appId: '1:214393173920:web:99fec2a75c22a1df4e96c5',
    messagingSenderId: '214393173920',
    projectId: 'recycleapp-6c4e6',
    authDomain: 'recycleapp-6c4e6.firebaseapp.com',
    storageBucket: 'recycleapp-6c4e6.firebasestorage.app',
    measurementId: 'G-Q75GCQP890',
  );
}
